### ISSUE TITLE
Are username and password values required?

### ISSUE THREAD

**Issue by rootd00d** [Appdynamics/appdynamics-charts#11]
The documentation says that the following is required --
```
controllerInfo:
  url: <controller-url>
  account: <controller-account>
  username: <controller-username>
  password: <controller-password>
  accessKey: <controller-accesskey>
```
Are the username and password fields really required, or is the access key sufficient, or vice-versa?
